language: node_js
sudo: false
node_js:
- '9.8'
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: LxJ7cxFbc44wPWsIwNTVKX3bdIh5XH9HnvV9eR6nScD0ubhahWuCPYts8A0BcVkY0Mk+/y4el5WCIvYTZcdCNYsqm2vUzRufNSFlzqaQN4e+HvRQ7f6ESpBVQ0JEcDl/hEFLWXPu4iz0TX2oS8Eo8k/2vK87gGSGnRuVvfclZ3DdReWcdu7fPgZ7a5QGtsDsFdX8tHcrMRCCc7apx88Sk8xH+DGqbSfQ7wKMHv0VRa7X1NIT8TftGj2HVGCiH1mGGa0nLi3IAt+i0AVcdfO+h5WKy+PQwPfcOKAiTTbumbhvUH+ScU5EReNhBqNk5+sn3BXvRt9z6sGDjklgCVKP7n610I1j7sXwXF5tTf8MJL6sFjLmLOv5ITk0YiYDEloYJaa0CpCvZiu/fQJJONRY36lvhsDohadoSwlkW0Kr9VbnYw4XsnNalu03/sC9WU+uBTSY0vzm/qUg9QZSDfJFEDYtJ2tdJIAgS/MAGwkYQ9m4PsRSezXlwjQ0TftW89Xnog6gC1o6ZjN5jCVqUUruO/l7Rp4Cq4piIDU3KmNcTKmMRgZvjiFvU9RPeqTd7SgGeEnhI+oQhAm8H1GtAaVMd1RlP2OI69vT9yhnVqWoYXjl0G5pAnZ2j7rgv3Y1fcUC6LCQPNeSwbDTrzBBivxdg3guY2MHS+BqLdp0BMed5dE=
  app: daddit
